import os
import json

base_dir = "backend/n8n/workflows/v3"

structure = {
    "00_INFRAESTRUTURA": [
        "000_ENV_CONFIG", "001_CREDENCIAIS_CHECK", "002_ERROR_HANDLER_GLOBAL",
        "003_LOGS_GLOBAIS", "004_HEALTHCHECK_GERAL", "005_BACKUP_WORKFLOWS",
        "006_MONITORAMENTO_CUSTOS_IA"
    ],
    "01_CANAIS_ENTRADA": [
        "010_WEBHOOK_SITE_COM", "011_WEBHOOK_SITE_COM_BR", "012_WHATSAPP_META_21992698612",
        "013_INSTAGRAM_DIRECT", "014_FACEBOOK_MESSENGER", "015_TIKTOK_COMENTARIOS_LEADS",
        "016_TELEGRAM_BOT", "017_GOOGLE_MEU_NEGOCIO", "018_HOSTGATOR_EMAIL_IMAP"
    ],
    "02_NORMALIZACAO": [
        "020_NORMALIZAR_PAYLOAD", "021_IDENTIFICAR_CANAL", "022_EXTRAIR_DADOS_CLIENTE",
        "023_EXTRAIR_SERVICO_INTERESSE", "024_DETECTAR_DUPLICIDADE", "025_DETECTAR_SPAM",
        "026_ENRIQUECER_LEAD"
    ],
    "03_AGENTES_CENTRAIS": [
        "030_ANINHA_TRIAGEM", "031_DIEGO_ROTEADOR", "032_MAILGUARD_HOSTGATOR",
        "033_SOCIAL_MEDIA_AGENT", "034_JULES_AUDITOR", "035_AGENT_ORCAMENTO",
        "036_AGENT_SUPORTE", "037_AGENT_FOLLOWUP"
    ],
    "04_MODELOS_IA": [
        "040_GEMINI_TRIAGEM_RAPIDA", "041_CHATGPT_COMERCIAL", "042_DEEPSEEK_TECNICO_CODIGO",
        "043_CLAUDE_ANALISE_LONGA", "044_ANTIGRAVITY_ORQUESTRACAO", "045_STITCH_INTEGRACOES_GOOGLE"
    ],
    "05_MEMORIA_BANCO": [
        "050_SUPABASE_LEADS", "051_SUPABASE_CONVERSAS", "052_SUPABASE_ATENDIMENTOS",
        "053_SUPABASE_ORCAMENTOS", "054_SUPABASE_CHAMADOS", "055_SUPABASE_POSTAGENS",
        "056_SUPABASE_CLIENTES", "057_SUPABASE_CONDOMINIOS", "058_SUPABASE_LOGS"
    ],
    "06_DECISAO_ROTEAMENTO": [
        "060_CLASSIFICAR_INTENCAO", "061_CLASSIFICAR_SERVICO", "062_CLASSIFICAR_PRIORIDADE",
        "063_DECIDIR_AGENTE", "064_DECIDIR_RESPOSTA_AUTOMATICA", "065_DECIDIR_HUMANO",
        "066_DECIDIR_VISITA_TECNICA", "067_DECIDIR_FOLLOWUP"
    ],
    "07_SERVICOS_DL": [
        "070_DL_GUARDIAO_SEGURANCA", "071_DL_ALERTA_INCENDIO", "072_DL_VOLT_ELETRICA",
        "073_DL_ECOVOLT_SOLAR", "074_DL_VOLTCHARGE_CARREGADOR", "075_DL_COMMANDER_AUTOMACAO",
        "076_DL_AQUA_BOMBAS", "077_DL_PARTNER_CONTRATOS"
    ],
    "08_CANAIS_SAIDA": [
        "080_WHATSAPP_ENVIAR", "081_INSTAGRAM_RESPONDER", "082_FACEBOOK_RESPONDER",
        "083_TELEGRAM_RESPONDER", "084_HOSTGATOR_EMAIL_SMTP", "085_GOOGLE_MEU_NEGOCIO_RESPONDER",
        "086_NOTIFICAR_DIOGO"
    ],
    "09_DOCUMENTOS_GOOGLE_DRIVE": [
        "090_CRIAR_PASTA_CLIENTE", "091_SALVAR_ANEXOS", "092_SALVAR_FOTOS_VIDEOS",
        "093_GERAR_RELATORIO_TECNICO", "094_GERAR_PROPOSTA", "095_GERAR_ORCAMENTO",
        "096_ORGANIZAR_ARQUIVOS"
    ],
    "10_POSTAGEM_AUTOMATICA": [
        "100_PLANEJADOR_EDITORIAL", "101_GERADOR_COPY", "102_GERADOR_ROTEIRO_VIDEO",
        "103_GERADOR_HASHTAGS", "104_APROVACAO_HUMANA", "105_PUBLICAR_INSTAGRAM",
        "106_PUBLICAR_FACEBOOK", "107_PUBLICAR_TIKTOK", "108_PUBLICAR_GOOGLE_MEU_NEGOCIO",
        "109_REGISTRAR_POSTAGEM"
    ],
    "11_PROCESSOS_COMERCIAIS": [
        "110_NOVO_LEAD", "111_QUALIFICAR_LEAD", "112_GERAR_OPORTUNIDADE", "113_SOLICITAR_FOTOS",
        "114_SOLICITAR_ENDERECO", "115_AGENDAR_VISITA", "116_ENVIAR_PROPOSTA", "117_FOLLOWUP_24H",
        "118_FOLLOWUP_72H", "119_REATIVAR_LEAD_FRIO"
    ],
    "12_PROCESSOS_TECNICOS": [
        "120_ABRIR_CHAMADO", "121_CLASSIFICAR_FALHA", "122_VERIFICAR_CONTRATO", "123_VERIFICAR_GARANTIA",
        "124_GERAR_PRE_DIAGNOSTICO", "125_ACIONAR_TECNICO", "126_REGISTRAR_VISITA", "127_REGISTRAR_SOLUCAO",
        "128_ENCERRAR_CHAMADO"
    ],
    "13_RELATORIOS": [
        "130_RELATORIO_DIARIO", "131_RELATORIO_LEADS", "132_RELATORIO_CONVERSAS", "133_RELATORIO_ORCAMENTOS",
        "134_RELATORIO_POSTAGENS", "135_RELATORIO_CHAMADOS", "136_RELATORIO_ERROS", "137_RELATORIO_TOKENS",
        "138_RELATORIO_EXECUTIVO"
    ],
    "14_TESTES_HOMOLOGACAO": [
        "140_TESTE_CANAIS_ENTRADA", "141_TESTE_CANAIS_SAIDA", "142_TESTE_HOSTGATOR_IMAP_SMTP",
        "143_TESTE_META_WHATSAPP", "144_TESTE_INSTAGRAM_FACEBOOK", "145_TESTE_TIKTOK",
        "146_TESTE_GOOGLE_DRIVE", "147_TESTE_GOOGLE_MEU_NEGOCIO", "148_TESTE_IA",
        "149_TESTE_SUPABASE", "150_TESTE_FLUXO_COMPLETO"
    ],
    "99_ADMIN": [
        "990_EXPORTAR_WORKFLOWS", "991_IMPORTAR_WORKFLOWS", "992_VALIDAR_TOKENS", "993_RENOVAR_TOKENS",
        "994_LIMPAR_LOGS", "995_MAPA_GERAL_N8N", "996_STATUS_INTEGRACOES", "997_ALERTA_WORKFLOW_PARADO",
        "998_BACKUP_GERAL", "999_PAINEL_DL_NEXUS"
    ]
}

def create_structure():
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)

    for folder, files in structure.items():
        folder_path = os.path.join(base_dir, folder)
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)

        for file in files:
            file_path = os.path.join(folder_path, f"{file}.json")
            if not os.path.exists(file_path):
                with open(file_path, 'w') as f:
                    # Provide basic n8n empty workflow JSON format
                    json.dump({
                      "name": file,
                      "nodes": [],
                      "connections": {},
                      "settings": {
                        "executionOrder": "v1"
                      }
                    }, f, indent=2)

if __name__ == "__main__":
    create_structure()
    print("V3 architecture created successfully.")
